module.exports=[93695,(a,b,c)=>{b.exports=a.x("next/dist/shared/lib/no-fallback-error.external.js",()=>require("next/dist/shared/lib/no-fallback-error.external.js"))},71306,(a,b,c)=>{b.exports=a.r(18622)},79847,a=>{a.n(a.i(3343))},9185,a=>{a.n(a.i(29432))},72842,a=>{a.n(a.i(75164))},54897,a=>{a.n(a.i(30106))},56157,a=>{a.n(a.i(18970))},94331,a=>{a.n(a.i(60644))},15988,a=>{a.n(a.i(56952))},25766,a=>{a.n(a.i(77341))},29725,a=>{a.n(a.i(94290))},5785,a=>{a.n(a.i(90588))},74793,a=>{a.n(a.i(33169))},85826,a=>{a.n(a.i(37111))},21565,a=>{a.n(a.i(41763))},65911,a=>{a.n(a.i(8950))},25128,a=>{a.n(a.i(91562))},40781,a=>{a.n(a.i(49670))},69411,a=>{a.n(a.i(75700))},63081,a=>{a.n(a.i(276))},62837,a=>{a.n(a.i(40795))},34607,a=>{a.n(a.i(11614))},96338,a=>{a.n(a.i(21751))},50642,a=>{a.n(a.i(12213))},32242,a=>{a.n(a.i(22693))},88530,a=>{a.n(a.i(10531))},8583,a=>{a.n(a.i(1082))},38534,a=>{a.n(a.i(98175))},70408,a=>{a.n(a.i(9095))},22922,a=>{a.n(a.i(96772))},78294,a=>{a.n(a.i(71717))},16625,a=>{a.n(a.i(85034))},88648,a=>{a.n(a.i(68113))},51914,a=>{a.n(a.i(66482))},25466,a=>{a.n(a.i(91505))},31843,a=>{"use strict";a.s(["default",()=>b]);let b=(0,a.i(11857).registerClientReference)(function(){throw Error("Attempted to call the default export of [project]/components/TaskInbox.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/components/TaskInbox.tsx <module evaluation>","default")},31898,a=>{"use strict";a.s(["default",()=>b]);let b=(0,a.i(11857).registerClientReference)(function(){throw Error("Attempted to call the default export of [project]/components/TaskInbox.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/components/TaskInbox.tsx","default")},33840,a=>{"use strict";a.i(31843);var b=a.i(31898);a.n(b)},80731,a=>{"use strict";var b=a.i(7997),c=a.i(33840),d=a.i(98310),e=a.i(18836),f=a.i(91032);async function g(a=new Date){let b=(0,d.getServiceSupabase)(),{data:c,error:h}=await b.from("renewal_tasks").select(`
      *,
      renewal_cycles!inner (
        id,
        renewal_date,
        status,
        members!inner (*)
      )
    `).eq("status","open").order("due_date",{ascending:!0});if(h)throw h;return[...(function(a){let b=new Map;for(let c of a){let a=b.get(c.member.id)??[];a.push(c),b.set(c.member.id,a)}return Array.from(b.values()).flatMap(a=>{var b;let c=a.map(a=>a.renewal_date).sort((a,b)=>a.localeCompare(b))[0],d=(b=a.filter(a=>a.renewal_date===c),f.activeRenewalTaskTypes.map(a=>b.find(b=>b.task_type===a&&"open"===b.status)).find(a=>!!a)??null);return d?[d]:[]})})((c??[]).filter(b=>b.renewal_cycles?.members&&"active"===b.renewal_cycles.status&&(0,e.isWithinRenewalWorkWindow)(b.renewal_cycles.renewal_date,a)).map(a=>({id:a.id,renewal_cycle_id:a.renewal_cycle_id,task_type:a.task_type,due_date:a.due_date,status:a.status,notes:a.notes,completed_at:a.completed_at,member:a.renewal_cycles.members,renewal_date:a.renewal_cycles.renewal_date}))).map(b=>({...b,...function(a,b=new Date){let c=function(a){let[b,c,d]=a.slice(0,10).split("-").map(Number);return new Date(Date.UTC(b,c-1,d))}(a),d=new Date(Date.UTC(b.getFullYear(),b.getMonth(),b.getDate())),e=Math.floor((c.getTime()-d.getTime())/864e5);return e<0?{urgency_score:100,urgency_label:"overdue",color:"red"}:e<=10?{urgency_score:70,urgency_label:"due_soon",color:"yellow"}:{urgency_score:30,urgency_label:"upcoming",color:"green"}}(b.due_date,a)}))].sort((a,b)=>b.urgency_score-a.urgency_score||a.due_date.localeCompare(b.due_date))}async function h(){let a=[],d=null;try{a=await g()}catch(a){d=a instanceof Error?a.message:"Unable to load task inbox"}return(0,b.jsxs)("div",{className:"space-y-6",children:[(0,b.jsxs)("div",{className:"flex flex-col gap-2",children:[(0,b.jsx)("p",{className:"text-sm font-medium text-[var(--accent)]",children:"Task Inbox"}),(0,b.jsx)("h1",{className:"text-3xl font-semibold tracking-normal",children:"Urgency Inbox"}),(0,b.jsx)("p",{className:"max-w-3xl text-sm text-[var(--muted)]",children:"Start with the most urgent open renewal task, then clear the queue."})]}),d?(0,b.jsxs)("div",{className:"rounded-md border border-[var(--line)] bg-white p-4",children:[(0,b.jsx)("h2",{className:"font-semibold",children:"Connect Supabase to load the inbox"}),(0,b.jsx)("p",{className:"mt-2 text-sm text-[var(--muted)]",children:d})]}):(0,b.jsx)(c.default,{tasks:a})]})}a.s(["default",0,h,"dynamic",0,"force-dynamic"],80731)},8801,a=>{a.n(a.i(80731))}];

//# sourceMappingURL=%5Broot-of-the-server%5D__1049_7a._.js.map