var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/tasks/inbox/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1049_7a._.js")
R.c("server/chunks/ssr/lib_0oepz6y._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0eujhhw.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-6_wq9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ngiev5._.js")
R.c("server/chunks/ssr/_05jr-yx._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_tasks_inbox_page_actions_094tg~~.js")
R.m(98661)
module.exports=R.m(98661).exports
